"""new fields in user model

Revision ID: 046a7e7254b8
Revises: 7ad0bc3ba327
Create Date: 2018-09-21 11:04:05.368056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046a7e7254b8'
down_revision = '7ad0bc3ba327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
